/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class Vista extends JFrame {

    /**
     * Creates new form Vista
     */
    private final Modelo modelo;
    private Controlador controlador;

    public Vista(Modelo modelo) {
        this.modelo = modelo;
        this.controlador = new Controlador(this, modelo);
        initComponents();
        agregarcontroladores();
        
    }
    
    public void agregarcontroladores()
    {
        this.addWindowListener(controlador);
        this.jBConectarse.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDatosConexion = new javax.swing.JPanel();
        jLDireccionIP = new javax.swing.JLabel();
        jTDireccionIP = new javax.swing.JTextField();
        jLPuerto = new javax.swing.JLabel();
        jTPuerto = new javax.swing.JTextField();
        jBConectarse = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jPTablero = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMensajes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPDatosConexion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLDireccionIP.setText("Direccion IP");

        jTDireccionIP.setText("localhost");

        jLPuerto.setText("Puerto");

        jTPuerto.setEditable(false);
        jTPuerto.setText("9090");

        jBConectarse.setText("Conectarse");

        jLNombre.setText("Nombre");

        jTNombre.setText("Cliente");

        javax.swing.GroupLayout jPDatosConexionLayout = new javax.swing.GroupLayout(jPDatosConexion);
        jPDatosConexion.setLayout(jPDatosConexionLayout);
        jPDatosConexionLayout.setHorizontalGroup(
            jPDatosConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosConexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLDireccionIP)
                .addGap(18, 18, 18)
                .addComponent(jTDireccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLPuerto)
                .addGap(18, 18, 18)
                .addComponent(jTPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLNombre)
                .addGap(18, 18, 18)
                .addComponent(jTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBConectarse)
                .addContainerGap())
        );
        jPDatosConexionLayout.setVerticalGroup(
            jPDatosConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosConexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDireccionIP)
                    .addComponent(jTDireccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPuerto)
                    .addComponent(jTPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConectarse)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPTablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPTableroLayout = new javax.swing.GroupLayout(jPTablero);
        jPTablero.setLayout(jPTableroLayout);
        jPTableroLayout.setHorizontalGroup(
            jPTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPTableroLayout.setVerticalGroup(
            jPTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTMensajes.setColumns(20);
        jTMensajes.setRows(5);
        jScrollPane1.setViewportView(jTMensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPDatosConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPDatosConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConectarse;
    private javax.swing.JLabel jLDireccionIP;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPuerto;
    private javax.swing.JPanel jPDatosConexion;
    private javax.swing.JPanel jPTablero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDireccionIP;
    private javax.swing.JTextArea jTMensajes;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPuerto;
    // End of variables declaration//GEN-END:variables

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public JButton getjBConectarse() {
        return jBConectarse;
    }

    public void setjBConectarse(JButton jBConectarse) {
        this.jBConectarse = jBConectarse;
    }

    public JLabel getjLDireccionIP() {
        return jLDireccionIP;
    }

    public void setjLDireccionIP(JLabel jLDireccionIP) {
        this.jLDireccionIP = jLDireccionIP;
    }

    public JLabel getjLPuerto() {
        return jLPuerto;
    }

    public void setjLPuerto(JLabel jLPuerto) {
        this.jLPuerto = jLPuerto;
    }

    public JPanel getjPDatosConexion() {
        return jPDatosConexion;
    }

    public void setjPDatosConexion(JPanel jPDatosConexion) {
        this.jPDatosConexion = jPDatosConexion;
    }

    public JPanel getjPTablero() {
        return jPTablero;
    }

    public void setjPTablero(JPanel jPTablero) {
        this.jPTablero = jPTablero;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getjTDireccionIP() {
        return jTDireccionIP;
    }

    public void setjTDireccionIP(JTextField jTDireccionIP) {
        this.jTDireccionIP = jTDireccionIP;
    }

    public JTextArea getjTMensajes() {
        return jTMensajes;
    }

    public void setjTMensajes(JTextArea jTMensajes) {
        this.jTMensajes = jTMensajes;
    }

    public JTextField getjTPuerto() {
        return jTPuerto;
    }

    public void setjTPuerto(JTextField jTPuerto) {
        this.jTPuerto = jTPuerto;
    }

    public JLabel getjLNombre() {
        return jLNombre;
    }

    public void setjLNombre(JLabel jLNombre) {
        this.jLNombre = jLNombre;
    }

    public JTextField getjTNombre() {
        return jTNombre;
    }

    public void setjTNombre(JTextField jTNombre) {
        this.jTNombre = jTNombre;
    }

       
    

}
